### ISSUE TITLE
Plugin keeps giving 500 errors

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-AppMon-SOAP-Monitor-Plugin#2]
Plugin gives 500 errors.

I have been able to do the requests in Postman, SoapUI, and with powershell. But I have not been able to perform them with this plugin.

**Comment by Dynatrace-James-Kitson** [comment]
I've pushed my commits but haven't created a new release yet. But what I found is there was a feature added and it included a switch between a number of options, and if the default if "None" was selected there was no switch for it so the result is that an empty POST body would be sent explaining the 500s. 

I was working on some changes to allow for basic authentication upfront when I came across the same issue.
